
export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/crop-yield', label: 'Crop Yield Prediction' },
  { href: '/ai-farmer', label: 'AI Farmer' },
  { href: '/disease-classification', label: 'Disease Classification' },
  { href: '/animal-classification', label: 'Animal Classification' },
  { href: '/govt-schemes', label: 'Govt. Schemes' },
];

export const featuresData = [
    {
        title: 'Crop Yield Prediction',
        description: 'Leverage AI to forecast your harvest and optimize your strategy.',
        imageUrl: 'https://picsum.photos/300/200?random=11',
        dataAiHint: 'crop yield',
        href: '/crop-yield'
    },
    {
        title: 'AI Farmer Assistant',
        description: 'Your personal agricultural expert, available 24/7.',
        imageUrl: '/images/ai-farmer-illustration.png',
        dataAiHint: 'farmer technology',
        href: '/ai-farmer'
    },
    {
        title: 'Disease Classification',
        description: 'Upload an image of a crop leaf to detect diseases early.',
        imageUrl: 'https://picsum.photos/300/200?random=13',
        dataAiHint: 'plant disease',
        href: '/disease-classification'
    },
    {
        title: 'Animal Classification',
        description: 'Identify animal species from an image, for livestock or wildlife.',
        imageUrl: 'https://picsum.photos/300/200?random=14',
        dataAiHint: 'farm animals',
        href: '/animal-classification'
    },
    {
        title: 'Govt. Schemes',
        description: 'Explore beneficial programs and support from the government.',
        imageUrl: 'https://picsum.photos/300/200?random=15',
        dataAiHint: 'government building',
        href: '/govt-schemes'
    },
];

export const newsCategories = [
  'All Categories',
  'Market Prices',
  'Weather Updates',
  'Government Policies',
  'Farming Techniques',
  'Technology',
];

export const newsData = [
  {
    id: 1,
    title: 'New Drone Technology Revolutionizes Crop Monitoring',
    source: 'AgriTech Today',
    date: 'October 26, 2023',
    snippet:
      'Advanced drones equipped with multispectral sensors are providing farmers with unprecedented insights into crop health, enabling early detection of stress and disease.',
    url: '#',
    category: 'Technology',
  },
  {
    id: 2,
    title: 'Government Announces Increased Subsidies for Organic Farming',
    source: 'Farmer\'s Journal',
    date: 'October 25, 2023',
    snippet:
      'In a move to promote sustainable agriculture, the government has rolled out a new package of subsidies aimed at farmers transitioning to or practicing organic farming methods.',
    url: '#',
    category: 'Government Policies',
  },
  {
    id: 3,
    title: 'Weather Patterns Shift: Farmers Adapt to a Changing Climate',
    source: 'Global Farming Initiative',
    date: 'October 24, 2023',
    snippet:
      'A new report highlights the innovative strategies farmers are adopting to cope with unpredictable weather, from drought-resistant crops to advanced irrigation systems.',
    url: '#',
    category: 'Weather Updates',
  },
    {
    id: 4,
    title: 'Corn Prices Surge Amidst Global Supply Concerns',
    source: 'Agri-Investments Daily',
    date: 'October 23, 2023',
    snippet: 'Analysts report a significant increase in corn futures as poor weather conditions in major producing regions threaten the global supply chain.',
    url: '#',
    category: 'Market Prices',
  },
  {
    id: 5,
    title: 'The Rise of No-Till Farming: A Guide for Beginners',
    source: 'Sustainable Farms',
    date: 'October 22, 2023',
    snippet: 'No-till farming is gaining popularity for its benefits to soil health and water conservation. This guide breaks down how to get started.',
    url: '#',
    category: 'Farming Techniques',
  },
  {
    id: 6,
    title: 'New AI-Powered App Helps Farmers Identify Pests Instantly',
    source: 'TechCrunch Agriculture',
    date: 'October 21, 2023',
    snippet: 'A startup has launched a mobile app that uses artificial intelligence to identify crop pests from a single photo, offering instant treatment recommendations.',
    url: '#',
    category: 'Technology',
  },
];

export const schemesData = [
  {
    id: 1,
    name: 'Pradhan Mantri Kisan Samman Nidhi',
    shortName: 'PM-KISAN',
    description: 'A government scheme with an objective to supplement the financial needs of all landholding farmers\' families in procuring various inputs to ensure proper crop health and appropriate yields, commensurate with the anticipated farm income.',
    imageUrl: 'https://picsum.photos/200/200?random=1',
    dataAiHint: 'government building',
    url: '#',
  },
  {
    id: 2,
    name: 'Pradhan Mantri Fasal Bima Yojana',
    shortName: 'PMFBY',
    description: 'The scheme provides insurance coverage and financial support to the farmers in the event of failure of any of the notified crop as a result of natural calamities, pests & diseases.',
    imageUrl: 'https://picsum.photos/200/200?random=2',
    dataAiHint: 'crop insurance',
    url: '#',
  },
  {
    id: 3,
    name: 'Kisan Credit Card (KCC)',
    shortName: 'KCC',
    description: 'The KCC scheme aims at providing adequate and timely credit support from the banking system under a single window with flexible and simplified procedure to the farmers for their cultivation and other needs.',
    imageUrl: 'https://picsum.photos/200/200?random=3',
    dataAiHint: 'credit card',
    url: '#',
  },
  {
    id: 4,
    name: 'National Mission for Sustainable Agriculture',
    shortName: 'NMSA',
    description: 'NMSA has been formulated for enhancing agricultural productivity especially in rainfed areas focusing on integrated farming, water use efficiency, soil health management and synergizing resource conservation.',
    imageUrl: 'https://picsum.photos/200/200?random=4',
    dataAiHint: 'sustainable agriculture',
    url: '#',
  },
];

export const farmingQuotes = [
  "Farming is not just a job, it’s a way of life.",
  "The farmer is the only man in our economy who buys everything at retail, sells everything at wholesale, and pays the freight both ways.",
  "Without farmers, there is no food. Without food, there is no life.",
  "To forget how to dig the earth and tend the soil is to forget ourselves.",
  "Farming is the art of patience, the science of soil, and the soul of survival.",
  "The ultimate goal of farming is not the growing of crops, but the cultivation of humans.",
  "Agriculture is the backbone of the nation.",
  "Farmers feed the world, yet they often eat last.",
  "When tillage begins, other arts follow. The farmers are the founders of human civilization.",
  "Soil is the great connector of lives, the source and destination of all.",
  "A farmer’s hands may be rough, but they grow the world’s softest bread.",
  "Farming is the profession of hope.",
  "Healthy soil, healthy food, healthy people.",
  "The best fertilizer for the land is the farmer’s footsteps.",
  "A society that forgets its farmers is a society without a future.",
  "Farming is the only business where you truly work with nature, not against it.",
  "The miracle of agriculture is turning a seed into a thousand meals.",
  "Farmers plant hope for the future in every seed.",
  "Good farmers take care of the soil, and the soil takes care of them.",
  "Farming is the greatest service to humanity.",
  "The future belongs to those who feed it.",
  "Rain or shine, farmers keep the world alive.",
  "Farmers don’t just grow crops, they grow nations.",
  "Every farmer is a scientist, experimenting with the earth.",
  "Respect the hands that feed you.",
  "A good farmer is nothing less than a hero.",
  "The land is more than soil; it is history, roots, and identity.",
  "In every seed lies a story of tomorrow.",
  "Farming is both tradition and innovation.",
  "A farmer’s sweat is sweeter than gold, because it grows life.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don’t farmers ever get lost? Because they always follow the tractor’s GPS… “Ground Positioning System.”",
  "Why did the cow go to space? To see the “milky way!”",
  "What did the farmer say after he lost his tractor? “Where’s my tractor?”",
  "Why did the tomato blush? Because it saw the farmer dressing his salad!",
  "Why did the farmer bring a pencil to the field? To draw his crops.",
  "What’s a farmer’s favorite type of music? “Crop” music.",
  "Why are farmers so good at math? Because they’re used to “multiplying” crops.",
  "Why was the farmer always calm? Because he knew how to “keep his peas.”",
  "What do farmers use to make crop circles? A pro-tractor!",
  "Why did the cow sit under the tree? Because it wanted some “moo-d” shade.",
  "Why do potatoes make good detectives? Because they keep their “eyes” open.",
  "What’s a farmer’s favorite type of joke? Corny ones. 🌽",
  "Why did the tractor blush? Because it saw the farmer plow-ing.",
  "Why don’t chickens ever tell secrets? Because they might “egg-spose” them.",
  "Why did the farmer plant a seed in his computer? To grow a website!",
  "Why are farmers good comedians? Because they have “field experience.”",
  "What did the farmer say when his crops were singing? “Sounds like a good harvest tune.”",
  "Why did the farmer start using AI? Because his crops needed a little “byte” of help.",
  "Why do cows wear bells? Because their horns don’t work!",
  "Without farmers, there is no food security.",
  "Every time you waste food, remember a farmer’s sweat went into it.",
  "Save water today, so crops can grow tomorrow.",
  "Support local farmers — they feed your community.",
  "Sustainable farming is the future of food.",
  "Healthy soil equals healthy generations.",
  "Climate change affects farmers first — act now.",
  "Fair price for farmers means fair food for all.",
  "Farmers don’t need sympathy, they need support.",
  "Buying local helps farmers survive.",
  "Use organic methods, protect future generations.",
  "Technology in farming can double food security.",
  "Protect the farmer, protect the nation.",
  "Farming is not just work, it’s service to humanity.",
  "A hungry farmer cannot feed a hungry nation.",
  "Agriculture is not an industry, it’s a lifeline.",
  "Invest in farmers, and you invest in the nation’s future.",
  "Respect food, respect farmers.",
  "Don’t take your plate for granted — thank a farmer.",
  "When farmers grow, nations prosper."
];
